GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order chicken"
}

###

DELETE http://localhost:3001/todo/delete/647c12ba2b51838b339004fd

###

PUT http://localhost:3001/todo/complete/6476d40debcf55f35330aabc